### ISSUE TITLE
MySQL postinst currently broken in master

### ISSUE THREAD

**Issue by dschallert** [open-as-team/open-as-cgw#17]
Mysql post-installation routine is currently broken in debian/open-as-cgw.postinst..

	*** Preparing System User Accounts... OK
	*** Preparing Crypto Configuration... OK
	*** Preparing Base System Configuration... OK
	*** Preparing SSH Configuration... OK
	*** Preparing Open AS Configuration... OK
	*** Preparing CLI Configuration... OK
	*** Preparing CRON Configuration... OK
	*** Preparing Postfix Configuration... OK
	*** Preparing PostFWD Configuration... OK
	*** Preparing Spamassassin Configuration... OK
	*** Preparing MySQL Configuration... dpkg: error processing package open-as-cgw (--configure):
	 subprocess installed post-installation script returned error exit status 1
	Errors were encountered while processing:
	 open-as-cgw
	E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by dschallert** [comment]
Should be fixed with 4d2f5b2

**Comment by dschallert** [comment]
Looks good now... 👍 

	[bash /var/lib/dpkg/info/open-as-cgw.postinst configure
	*** Preparing System User Accounts... OK
	*** Preparing Crypto Configuration... OK
	*** Preparing Base System Configuration... OK
	*** Preparing SSH Configuration... OK
	*** Preparing Open AS Configuration... OK
	*** Preparing CLI Configuration... OK
	*** Preparing CRON Configuration... OK
	*** Preparing Postfix Configuration... OK
	*** Preparing PostFWD Configuration... OK
	*** Preparing Spamassassin Configuration... OK
	*** Preparing MySQL Configuration... OK
	*** Preparing Nginx Configuration... OK
	*** Preparing LDAP Configuration... OK
	*** Preparing Quarantine... OK
	*** Preparing SMTPCrypt Configuration...OK
	*** Preparing network/interfaces... OK
	Starting Open AS Firewall: openas-firewall.
	Starting Open AS rtlogd: (already running).
	Starting Open AS Quarantine Cron: openas-qcron.
	Starting Open AS Quarantine NG: openas-qng.
	Starting Open AS Backend: openas-backend.
	Starting Open AS Firewall: openas-firewall.
	Starting Open AS rtlogd: (already running).
	Starting Open AS Quarantine Cron: openas-qcron.
	Starting Open AS Quarantine NG: openas-qng.
	Starting Open AS Backend: openas-backend.

**Comment by ncsatech** [comment]
I keep getting this same error trying to install this app.  How do I get this working.

Setting up open-as-cgw (2.1.0-0~146~ubuntu14.04.1) ...
*** Preparing System User Accounts... OK
*** Preparing Crypto Configuration... OK
*** Preparing Base System Configuration... OK
*** Preparing SSH Configuration... OK
*** Preparing Open AS Configuration... OK
*** Preparing CLI Configuration... OK
*** Preparing CRON Configuration... OK
*** Preparing Postfix Configuration... OK
*** Preparing PostFWD Configuration... OK
*** Preparing Spamassassin Configuration... OK
*** Preparing Clamd Antivirus... OK
*** Preparing MySQL Configuration... FAILED
dpkg: error processing package open-as-cgw (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 open-as-cgw
E: Sub-process /usr/bin/dpkg returned an error code (1)


Thanks!
