### ISSUE TITLE
wildcard for recipient domains - accept all mails for certain domains

### ISSUE THREAD

**Issue by dschallert** [open-as-team/open-as-cgw#22]
> Hi together,
> 
> i am searching for a possibility to just accept all possible e-mail adresses by a domain. So just *@domain.tld .
> 
> Is there any way to set this in the preferences under MAIL TRANSFER --> RECIPIENTS to just allow all possible mailadresses of a given domain through the filter? (because there is a catchall-mailbox on the taget postfix server...)
> 
> kind regards
> Fabian

Source: https://forum.openas.org/index.php?topic=320.0

**Comment by esonn** [comment]
...shouldn't this be covered in "Envelope Scanning -> Black/-Whitelist Manager"?

**Comment by dschallert** [comment]
![Uploading Bildschirmfoto 2016-06-20 um 16.43.55.png…]()

Agreed. Closing this issue for now.
