### ISSUE TITLE
Cant start GUI in Ubuntu 16.04

### ISSUE THREAD

**Issue by siucdude** [open-as-team/open-as-cgw#44]
I get this when I try to run the GUI

~ % sudo /usr/bin/perl /var/www/LimesGUI/script/limesgui_server.pl
ERROR: Necessary path information missing. (Did you define LIMESLIB and LIMESGUI in ENV?)
<img width="1053" alt="screen shot 2016-08-18 at 3 08 31 pm" src="https://cloud.githubusercontent.com/assets/6015094/17788959/a9d5524a-6555-11e6-97aa-85853d64685c.png">

**Comment by schallertd** [comment]
Hi,
have you set the `LIMESLIB` and `LIMESGUI` env vars?

Please try a
`sudo /bin/bash /vagrant/lib/bin/set_dev_environment.sh`
before starting the GUI manually.

Thanks

**Comment by schallertd** [comment]
Closing this for now.

**Comment by krisgermann** [comment]
[root@antispam:/] $ git clone https://github.com/open-as-team/open-as-cgw && cd open-as-cgw
Cloning into 'open-as-cgw'...
remote: Counting objects: 3435, done.
remote: Total 3435 (delta 0), reused 0 (delta 0), pack-reused 3435
Receiving objects: 100% (3435/3435), 4.44 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1991/1991), done.
Checking connectivity... done.
[root@antispam:/open-as-cgw] $ sudo /bin/bash ./lib/bin/set_dev_environment.sh
+ Appending variables to your ~/.bashrc...
+ Done! Please exit and re-login to your current shell!

After reboot I get:

root@antispam:~$ sudo /usr/bin/perl /var/www/LimesGUI/script/limesgui_server.pl
ERROR: Necessary path information missing. (Did you define LIMESLIB and LIMESGUI in ENV?)

**Comment by krisgermann** [comment]
Additionally, now every time I sudo su I get:

user@antispam:~$ sudo su
No command 'Open' found, did you mean:
 Command 'open' from package 'kbd' (main)
 Command 'pen' from package 'pen' (universe)
Open: command not found
