### ISSUE TITLE
Installation questions

### ISSUE THREAD

**Issue by Schaussi** [open-as-team/open-as-cgw#48]
Hi,

sorry to write an issue for this, but the forum seems to be down and the documentation link does not work.
The Open AS screenshots look very interesting, so I would like to test it, but had no luck so far:

Ubuntu 14.04: Tried the repository as mentioned on openas.org, but it contains only content for Ubuntu 16. So I tried this distro. The package installation ended successful, but instead of the web interface I see a custom error 500 page ("something went wrong with the gui").

Please give me some information about the correct way to install Open AS. As an alternative, is there already a fixed date when virtual appliance images would be available?

Thank you

**Comment by dominic1134** [comment]
Hi there,

we're currently working on a new release which will be based on Ubuntu 16.04.2 LTS and available as an appliance. You can find the old packages for Ubuntu 14.02 at https://launchpad.net/~esonn/+archive/ubuntu/open-as-cgw

Thanks

**Comment by Schaussi** [comment]
Could you tell me an approximate release date for the appliance?
Thank you
